#! /bin/bash

PACKAGE="phpqladmin"
VERSION="2.0.13-1"

. /usr/share/debconf/confmodule

db_subst "phpqladmin/webserver" "webserver" "Apache" || true
db_input medium "phpqladmin/webserver" || true
db_go

exit 0
