  <table cellspacing="0" cellpadding="0" border="0">
    <th valign="top" align="left">Locals
      <!-- LOCALS -->
      <?php include("./tables/control_details-hosts_locals.inc"); ?>
    </th>

    <th>&nbsp;&nbsp;&nbsp;&nbsp;</th>

    <th valign="top" align="left">RCPT Hosts
      <!-- RCPTHOSTS -->
      <?php include("./tables/control_details-hosts_rcpt.inc"); ?>
    </th>
  </table>

  <br><br>

<?php
/*
 * Local variables:
 * mode: php
 * mode: font-lock
 * tab-width: 4
 * End:
 */
?>
