  <table cellspacing="0" cellpadding="3" border="0">
    <th align="left"><?=PQL_LANG_ACTIONS?></th>
      <tr class="subtitle">
        <td colspan="4"><a href="installmailserver.php?domain=<?=$domain?>&mxhost=<?=$mxhost?>"><img src="images/edit.png" width="12" height="12" border="0">Create mailserver install script</a></td>
      </tr>

      <tr class="<?php table_bgcolor(); ?>">
        <td><a href="control_del.php?mxhost=<?=$mxhost?>"><img src="images/edit.png" width="12" height="12" border="0">Delete mailserver control object</a></td>
      </tr>
    </th>
  </table>
