<?php
// control attribute plugin for
// pbsenv
//
// $Id: attrib.control.pbsenv.inc,v 2.1 2004-04-01 06:56:07 turbo Exp $

// {{{ pbsenv_check(type)
function pbsenv_check($type) {
}
// }}}

// {{{ pbsenv_init(host)
function pbsenv_init($host) {
}
// }}}


// {{{ pbsenv_print_view(host)
function pbsenv_print_view($host) {
}
// }}}

// {{{ pbsenv_print_form(void)
function pbsenv_print_form() {
}
// }}}

// {{{ pbsenv_save(type, host)
function pbsenv_save($type, $host) {
}
// }}}


// {{{ pbsenv_help(void)
function pbsenv_help() {
}
// }}}

// {{{ pbsenv_help_cr(void)
function pbsenv_help_cr() {
	global $LANG;
	echo $LANG->_('Help text taken from life with qmail-ldap');
}
// }}}

// Local variables:
// mode: php
// mode: font-lock
// tab-width: 4
// End:
?>
