<?php
// control attribute plugin for
// pbsip
//
// $Id: attrib.control.pbsip.inc,v 2.1 2004-04-01 06:56:07 turbo Exp $

// {{{ pbsip_check(type)
function pbsip_check($type) {
}
// }}}

// {{{ pbsip_init(host)
function pbsip_init($host) {
}
// }}}


// {{{ pbsip_print_view(host)
function pbsip_print_view($host) {
}
// }}}

// {{{ pbsip_print_form(void)
function pbsip_print_form() {
}
// }}}

// {{{ pbsip_save(type, host)
function pbsip_save($type, $host) {
}
// }}}


// {{{ pbsip_help(void)
function pbsip_help() {
}
// }}}

// {{{ pbsip_help_cr(void)
function pbsip_help_cr() {
	global $LANG;
	echo $LANG->_('Help text taken from life with qmail-ldap');
}
// }}}

// Local variables:
// mode: php
// mode: font-lock
// tab-width: 4
// End:
?>
