<?php
// control attribute plugin for
// qmqpcip
//
// $Id: attrib.control.qmqpcip.inc,v 2.1 2004-04-01 06:56:07 turbo Exp $

// {{{ qmqpcip_check(type)
function qmqpcip_check($type) {
}
// }}}

// {{{ qmqpcip_init(host)
function qmqpcip_init($host) {
}
// }}}


// {{{ qmqpcip_print_view(host)
function qmqpcip_print_view($host) {
}
// }}}

// {{{ qmqpcip_print_form(void)
function qmqpcip_print_form() {
}
// }}}

// {{{ qmqpcip_save(type, host)
function qmqpcip_save($type, $host) {
}
// }}}


// {{{ qmqpcip_help(void)
function qmqpcip_help() {
}
// }}}

// {{{ qmqpcip_help_cr(void)
function qmqpcip_help_cr() {
	global $LANG;
	echo $LANG->_('Help text taken from life with qmail-ldap');
}
// }}}

// Local variables:
// mode: php
// mode: font-lock
// tab-width: 4
// End:
?>
