<?php
// control attribute plugin for
// bouncesize
//
// $Id: attrib.control.bouncesize.inc,v 2.1 2004-04-01 06:56:07 turbo Exp $

// {{{ bouncesize_check(type)
function bouncesize_check($type) {
}
// }}}

// {{{ bouncesize_init(host)
function bouncesize_init($host) {
}
// }}}


// {{{ bouncesize_print_view(host)
function bouncesize_print_view($host) {
}
// }}}

// {{{ bouncesize_print_form(void)
function bouncesize_print_form() {
}
// }}}

// {{{ bouncesize_save(type, host)
function bouncesize_save($type, $host) {
}
// }}}


// {{{ bouncesize_help(void)
function bouncesize_help() {
}
// }}}

// {{{ bouncesize_help_cr(void)
function bouncesize_help_cr() {
	global $LANG;
	echo $LANG->_('Help text taken from life with qmail-ldap');
}
// }}}

// Local variables:
// mode: php
// mode: font-lock
// tab-width: 4
// End:
?>
