<?php
// control attribute plugin for
// ldaptimeout
//
// $Id: attrib.control.ldaptimeout.inc,v 2.1 2004-04-01 06:56:07 turbo Exp $

// {{{ ldaptimeout_check(type)
function ldaptimeout_check($type) {
}
// }}}

// {{{ ldaptimeout_init(host)
function ldaptimeout_init($host) {
}
// }}}


// {{{ ldaptimeout_print_view(host)
function ldaptimeout_print_view($host) {
}
// }}}

// {{{ ldaptimeout_print_form(void)
function ldaptimeout_print_form() {
}
// }}}

// {{{ ldaptimeout_save(type, host)
function ldaptimeout_save($type, $host) {
}
// }}}


// {{{ ldaptimeout_help(void)
function ldaptimeout_help() {
}
// }}}

// {{{ ldaptimeout_help_cr(void)
function ldaptimeout_help_cr() {
	global $LANG;
	echo $LANG->_('Help text taken from life with qmail-ldap');
}
// }}}

// Local variables:
// mode: php
// mode: font-lock
// tab-width: 4
// End:
?>
