<?php
// control attribute plugin for
// rbllist
//
// $Id: attrib.control.rbllist.inc,v 2.1 2004-04-01 06:56:07 turbo Exp $

// {{{ rbllist_check(type)
function rbllist_check($type) {
}
// }}}

// {{{ rbllist_init(host)
function rbllist_init($host) {
}
// }}}


// {{{ rbllist_print_view(host)
function rbllist_print_view($host) {
}
// }}}

// {{{ rbllist_print_form(void)
function rbllist_print_form() {
}
// }}}

// {{{ rbllist_save(type, host)
function rbllist_save($type, $host) {
}
// }}}


// {{{ rbllist_help(void)
function rbllist_help() {
}
// }}}

// {{{ rbllist_help_cr(void)
function rbllist_help_cr() {
	global $LANG;
	echo $LANG->_('Help text taken from life with qmail-ldap');
}
// }}}

// Local variables:
// mode: php
// mode: font-lock
// tab-width: 4
// End:
?>
