<?php
// attribute for phpQLAdmin/Password Policies - user entries
// $Id: attrib.ppolicy.inc,v 2.1 2007-03-06 10:24:16 turbo Exp $

// {{{ attribute_check_ppolicy(void)
function attribute_check_ppolicy() {
}
// }}}

// {{{ attribute_init(void)
function attribute_init() {
}
// }}}

// {{{ attribute_print_form(void)
function attribute_print_form() {
}
// }}}

// {{{ attribute_save(void)
function attribute_save() {
}
// }}}

// Local variables:
// mode: php
// mode: font-lock
// tab-width: 4
// End:
?>
