<?php
// control attribute plugin for
// pbsservers
//
// $Id: attrib.control.pbsservers.inc,v 2.1 2004-04-01 06:56:07 turbo Exp $

// {{{ pbsservers_check(type)
function pbsservers_check($type) {
}
// }}}

// {{{ pbsservers_init(host)
function pbsservers_init($host) {
}
// }}}


// {{{ pbsservers_print_view(host)
function pbsservers_print_view($host) {
}
// }}}

// {{{ pbsservers_print_form(void)
function pbsservers_print_form() {
}
// }}}

// {{{ pbsservers_save(type, host)
function pbsservers_save($type, $host) {
}
// }}}


// {{{ pbsservers_help(void)
function pbsservers_help() {
}
// }}}

// {{{ pbsservers_help_cr(void)
function pbsservers_help_cr() {
	global $LANG;
	echo $LANG->_('Help text taken from life with qmail-ldap');
}
// }}}

// Local variables:
// mode: php
// mode: font-lock
// tab-width: 4
// End:
?>
