<?php
// control attribute plugin for
// pbstimeout
//
// $Id: attrib.control.pbstimeout.inc,v 2.1 2004-04-01 06:56:07 turbo Exp $

// {{{ pbstimeout_check(type)
function pbstimeout_check($type) {
}
// }}}

// {{{ pbstimeout_init(host)
function pbstimeout_init($host) {
}
// }}}


// {{{ pbstimeout_print_view(host)
function pbstimeout_print_view($host) {
}
// }}}

// {{{ pbstimeout_print_form(void)
function pbstimeout_print_form() {
}
// }}}

// {{{ pbstimeout_save(type, host)
function pbstimeout_save($type, $host) {
}
// }}}


// {{{ pbstimeout_help(void)
function pbstimeout_help() {
}
// }}}

// {{{ pbstimeout_help_cr(void)
function pbstimeout_help_cr() {
	global $LANG;
	echo $LANG->_('Help text taken from life with qmail-ldap');
}
// }}}

// Local variables:
// mode: php
// mode: font-lock
// tab-width: 4
// End:
?>
