<?php
// control attribute plugin for
// pbssecret
//
// $Id: attrib.control.pbssecret.inc,v 2.1 2004-04-01 06:56:07 turbo Exp $

// {{{ pbssecret_check(type)
function pbssecret_check($type) {
}
// }}}

// {{{ pbssecret_init(host)
function pbssecret_init($host) {
}
// }}}


// {{{ pbssecret_print_view(host)
function pbssecret_print_view($host) {
}
// }}}

// {{{ pbssecret_print_form(void)
function pbssecret_print_form() {
}
// }}}

// {{{ pbssecret_save(type, host)
function pbssecret_save($type, $host) {
}
// }}}


// {{{ pbssecret_help(void)
function pbssecret_help() {
}
// }}}

// {{{ pbssecret_help_cr(void)
function pbssecret_help_cr() {
	global $LANG;
	echo $LANG->_('Help text taken from life with qmail-ldap');
}
// }}}

// Local variables:
// mode: php
// mode: font-lock
// tab-width: 4
// End:
?>
