<?php
// control attribute plugin for
// pbsport
//
// $Id: attrib.control.pbsport.inc,v 2.1 2004-04-01 06:56:07 turbo Exp $

// {{{ pbsport_check(type)
function pbsport_check($type) {
}
// }}}

// {{{ pbsport_init(host)
function pbsport_init($host) {
}
// }}}


// {{{ pbsport_print_view(host)
function pbsport_print_view($host) {
}
// }}}

// {{{ pbsport_print_form(void)
function pbsport_print_form() {
}
// }}}

// {{{ pbsport_save(type, host)
function pbsport_save($type, $host) {
}
// }}}


// {{{ pbsport_help(void)
function pbsport_help() {
}
// }}}

// {{{ pbsport_help_cr(void)
function pbsport_help_cr() {
	global $LANG;
	echo $LANG->_('Help text taken from life with qmail-ldap');
}
// }}}

// Local variables:
// mode: php
// mode: font-lock
// tab-width: 4
// End:
?>
