<?php
// control attribute plugin for
// smtpClusterCookie
//
// $Id: attrib.control.ldapclustercookie.inc,v 2.1 2004-04-01 06:56:07 turbo Exp $

// {{{ ldapclustercookie_check(type)
function ldapclustercookie_check($type) {
}
// }}}

// {{{ ldapclustercookie_init(host)
function ldapclustercookie_init($host) {
}
// }}}


// {{{ ldapclustercookie_print_view(host)
function ldapclustercookie_print_view($host) {
}
// }}}

// {{{ ldapclustercookie_print_form(void)
function ldapclustercookie_print_form() {
}
// }}}

// {{{ ldapclustercookie_save(type, host)
function ldapclustercookie_save($type, $host) {
}
// }}}


// {{{ ldapclustercookie_help(void)
function ldapclustercookie_help() {
}
// }}}

// {{{ ldapclustercookie_help_cr(void)
function ldapclustercookie_help_cr() {
	global $LANG;
	echo $LANG->_('Help text taken from life with qmail-ldap');
}
// }}}

// Local variables:
// mode: php
// mode: font-lock
// tab-width: 4
// End:
?>
