<?php
// control attribute plugin for
// ldapClusterHosts
//
// $Id: attrib.control.ldapclusterhosts.inc,v 2.1 2004-04-01 06:56:07 turbo Exp $

// {{{ ldapclusterhosts_check(type)
function ldapclusterhosts_check($type) {
}
// }}}

// {{{ ldapclusterhosts_init(host)
function ldapclusterhosts_init($host) {
}
// }}}


// {{{ ldapclusterhosts_print_view(host)
function ldapclusterhosts_print_view($host) {
}
// }}}

// {{{ ldapclusterhosts_print_form(void)
function ldapclusterhosts_print_form() {
}
// }}}

// {{{ ldapclusterhosts_save(type, host)
function ldapclusterhosts_save($type, $host) {
}
// }}}


// {{{ ldapclusterhosts_help(void)
function ldapclusterhosts_help() {
}
// }}}

// {{{ ldapclusterhosts_help_cr(void)
function ldapclusterhosts_help_cr() {
	global $LANG;
	echo $LANG->_('Help text taken from life with qmail-ldap');
}
// }}}

// Local variables:
// mode: php
// mode: font-lock
// tab-width: 4
// End:
?>
