<?php
// control attribute plugin for
// pbscachesize
//
// $Id: attrib.control.pbscachesize.inc,v 2.1 2004-04-01 06:56:07 turbo Exp $

// {{{ pbscachesize_check(type)
function pbscachesize_check($type) {
}
// }}}

// {{{ pbscachesize_init(host)
function pbscachesize_init($host) {
}
// }}}


// {{{ pbscachesize_print_view(host)
function pbscachesize_print_view($host) {
}
// }}}

// {{{ pbscachesize_print_form(void)
function pbscachesize_print_form() {
}
// }}}

// {{{ pbscachesize_save(type, host)
function pbscachesize_save($type, $host) {
}
// }}}


// {{{ pbscachesize_help(void)
function pbscachesize_help() {
}
// }}}

// {{{ pbscachesize_help_cr(void)
function pbscachesize_help_cr() {
	global $LANG;
	echo $LANG->_('Help text taken from life with qmail-ldap');
}
// }}}

// Local variables:
// mode: php
// mode: font-lock
// tab-width: 4
// End:
?>
