<?php
// control attribute plugin for
// goodaddress
//
// $Id: attrib.control.goodaddress.inc,v 2.1 2004-04-01 06:56:07 turbo Exp $

// {{{ goodaddress_check(type)
function goodaddress_check($type) {
}
// }}}

// {{{ goodaddress_init(host)
function goodaddress_init($host) {
}
// }}}


// {{{ goodaddress_print_view(host)
function goodaddress_print_view($host) {
}
// }}}

// {{{ goodaddress_print_form(void)
function goodaddress_print_form() {
}
// }}}

// {{{ goodaddress_save(type, host)
function goodaddress_save($type, $host) {
}
// }}}


// {{{ goodaddress_help(void)
function goodaddress_help() {
}
// }}}

// {{{ goodaddress_help_cr(void)
function goodaddress_help_cr() {
	global $LANG;
	echo $LANG->_('Help text taken from life with qmail-ldap');
}
// }}}

// Local variables:
// mode: php
// mode: font-lock
// tab-width: 4
// End:
?>
