<?php
// control attribute plugin for
// outgoingip
//
// $Id: attrib.control.outgoingip.inc,v 2.1 2004-04-01 06:56:07 turbo Exp $

// {{{ outgoingip_check(type)
function outgoingip_check($type) {
}
// }}}

// {{{ outgoingip_init(host)
function outgoingip_init($host) {
}
// }}}


// {{{ outgoingip_print_view(host)
function outgoingip_print_view($host) {
}
// }}}

// {{{ outgoingip_print_form(void)
function outgoingip_print_form() {
}
// }}}

// {{{ outgoingip_save(type, host)
function outgoingip_save($type, $host) {
}
// }}}


// {{{ outgoingip_help(void)
function outgoingip_help() {
}
// }}}

// {{{ outgoingip_help_cr(void)
function outgoingip_help_cr() {
	global $LANG;
	echo $LANG->_('Help text taken from life with qmail-ldap');
}
// }}}

// Local variables:
// mode: php
// mode: font-lock
// tab-width: 4
// End:
?>
