<?php
// ----------------------------
// pql_ezmlm.inc
// phpQLAdmin Application Programming Interface (API)
//
// $Id: pql_krbafs.inc,v 1.1 2003-01-03 12:14:26 turbo Exp $

// Requires the OpenAFS JavaAPI
// http://grand.central.org/twiki/bin/view/AFSLore/JavaAPI

// Kerberos V functions
function kinit() {
}

function kdestroy() {
}

function kadmin_ank() {
}

function kadmin_delprinc() {
}

function kadmin_cpw() {
}

function kadmin_modprinc() {
}

// AFS functions
function aklog() {
}

function unlog() {
}

function createuser() {
}

function deleteuser() {
}

function createvolume() {
}

function removevolume() {
}

function setacl() {
}

function setquota() {
}


/*
 * Local variables:
 * mode: php
 * mode: font-lock
 * tab-width: 4
 * End:
 */
?>

